"""
render_html_view.py -- mirrors every *.md file under --out_root into an equivalent *.html file,
written alongside the original (same directory, same basename, .html extension), so relative
links keep working with just an extension swap. Does NOT modify or read-back the .md files
themselves in any destructive way -- pure additive output, safe to re-run any time after the
normal write_findings.py / plot_arch_hash.py / write_overall_best_archs.py pipeline has produced
its usual .md tree.

Why this exists: VS Code's Markdown Preview navigates IN PLACE when you click a link (replaces
the current preview, no new tab/window). Opening the .html twins in an actual browser instead
gives real new-tab/new-window behavior via Ctrl+Click / middle-click -- the standard web
convention, not available for plain markdown links in an editor.

Hand-rolled markdown -> HTML converter (no python-markdown dependency) -- every .md file in this
tree is machine-generated by this project's own scripts, so only a small, known subset of
markdown syntax ever appears: headers (#/##/###), **bold**, `code`, - bullet lists,
| table | rows |, ![images](...), [links](...), and 4-space-indented code blocks (the equation
writeups). A minimal line-based converter covers all of it correctly without a general parser.

Internal links (e.g. [text](foo.md)) are rewritten foo.md -> foo.html so the whole tree stays
click-through-able; links to non-.md assets (.png, .va) and http(s) URLs are left untouched.

Usage:
    python render_html_view.py --out_root ../runs/csv_base_2.5_20/best_archs_plots
    python render_html_view.py --out_root ... --workers 16
"""
from __future__ import annotations

import argparse
import html
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

_INLINE_CODE_RE = re.compile(r"`([^`]+)`")
_BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")
_IMG_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
_HEADER_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_BULLET_RE = re.compile(r"^- (.*)$")
_TABLE_SEP_RE = re.compile(r"^\|[\s:|-]+\|$")
# matches the literal '**(tanh-only)**' marker AFTER it's already become <strong>(tanh-only)</strong>
# (see find_consistent_archs.arch_link_cell) -- recolored red here, in this view only; plain bold
# everywhere the raw .md is read directly (VS Code preview, etc).
_TANH_ONLY_RE = re.compile(r"<strong>\(tanh-only\)</strong>")

_PAGE_TEMPLATE = """<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
:root {{ color-scheme: light dark; }}
body {{ font-family: -apple-system, "Segoe UI", sans-serif; max-width: 1100px; margin: 2rem auto;
        padding: 0 1rem; line-height: 1.5; }}
table {{ border-collapse: collapse; margin: 1rem 0; width: 100%; }}
th, td {{ border: 1px solid #88888844; padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; }}
th {{ background: #80808022; }}
img {{ max-width: 100%; height: auto; display: block; margin: 0.5rem 0; }}
pre {{ background: #80808014; padding: 0.75rem; overflow-x: auto; border-radius: 4px; }}
code {{ font-family: ui-monospace, Consolas, monospace; }}
a {{ color: #4098d7; }}
h1, h2, h3 {{ border-bottom: 1px solid #88888844; padding-bottom: 0.3rem; }}
.tanh-only {{ color: #e5484d; }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def _rewrite_href(href: str) -> str:
    """foo.md -> foo.html (path part only, before any #fragment/?query); everything else
    (png, va, http(s) urls, non-.md links) passes through untouched."""
    path, sep, rest = href.partition("#")
    if not sep:
        path, sep, rest = href.partition("?")
    if path.lower().endswith(".md"):
        path = path[:-3] + ".html"
    return path + sep + rest


def _inline(escaped_text: str) -> str:
    """Apply inline markdown formatting to an ALREADY html.escape()-d line: images, links, bold,
    inline code -- images before links so ![...] isn't eaten by the plain link pattern first."""
    def _img(m):
        return f'<img src="{_rewrite_href(m.group(2))}" alt="{m.group(1)}">'
    text = _IMG_RE.sub(_img, escaped_text)

    def _link(m):
        return f'<a href="{_rewrite_href(m.group(2))}">{m.group(1)}</a>'
    text = _LINK_RE.sub(_link, text)

    text = _BOLD_RE.sub(r"<strong>\1</strong>", text)
    text = _TANH_ONLY_RE.sub('<strong class="tanh-only">(tanh-only)</strong>', text)
    text = _INLINE_CODE_RE.sub(r"<code>\1</code>", text)
    return text


def convert(md_text: str, title: str) -> str:
    lines = md_text.split("\n")
    out = []
    i, n = 0, len(lines)
    in_list = False

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    while i < n:
        raw = lines[i]

        # indented code block: a maximal run of blank-or-4-space-indented lines, bounded by
        # non-indented content -- rendered verbatim (no inline formatting), used for the
        # equation writeups (plot_saved_state_full.md).
        if raw.startswith("    ") or raw.startswith("\t"):
            close_list()
            block = []
            while i < n and (lines[i].strip() == "" or lines[i].startswith("    ") or lines[i].startswith("\t")):
                block.append(lines[i])
                i += 1
            while block and block[-1].strip() == "":
                block.pop()
            while block and block[0].strip() == "":
                block.pop(0)
            code = "\n".join(l[4:] if l.startswith("    ") else l.lstrip("\t") for l in block)
            out.append(f"<pre><code>{html.escape(code)}</code></pre>")
            continue

        line = raw.rstrip()

        if line == "":
            close_list()
            i += 1
            continue

        # table: a '|'-led line followed by a '|---|' separator row
        if line.startswith("|") and i + 1 < n and _TABLE_SEP_RE.match(lines[i + 1].strip()):
            close_list()
            header_cells = [c.strip() for c in line.strip().strip("|").split("|")]
            out.append("<table><thead><tr>" +
                        "".join(f"<th>{_inline(html.escape(c))}</th>" for c in header_cells) +
                        "</tr></thead><tbody>")
            i += 2
            while i < n and lines[i].strip().startswith("|"):
                row_cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                out.append("<tr>" + "".join(f"<td>{_inline(html.escape(c))}</td>" for c in row_cells) + "</tr>")
                i += 1
            out.append("</tbody></table>")
            continue

        m = _HEADER_RE.match(line)
        if m:
            close_list()
            level = len(m.group(1))
            out.append(f"<h{level}>{_inline(html.escape(m.group(2)))}</h{level}>")
            i += 1
            continue

        m = _BULLET_RE.match(line)
        if m:
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_inline(html.escape(m.group(1)))}</li>")
            i += 1
            continue

        close_list()
        out.append(f"<p>{_inline(html.escape(line))}</p>")
        i += 1

    close_list()
    return _PAGE_TEMPLATE.format(title=html.escape(title), body="\n".join(out))


def convert_file(md_path: Path) -> Path:
    text = md_path.read_text(encoding="utf-8")
    out_path = md_path.with_suffix(".html")
    out_path.write_text(convert(text, md_path.stem), encoding="utf-8")
    return out_path


def render_tree(out_root: Path, workers: int) -> tuple[int, list[tuple[Path, Exception]]]:
    md_files = sorted(out_root.rglob("*.md"))
    print(f"converting {len(md_files)} .md files under {out_root} (workers={workers}) ...")
    ok = 0
    errors: list[tuple[Path, Exception]] = []
    with ThreadPoolExecutor(max_workers=workers) as ex:
        futs = {ex.submit(convert_file, p): p for p in md_files}
        for fut in as_completed(futs):
            p = futs[fut]
            try:
                fut.result()
                ok += 1
            except (OSError, UnicodeDecodeError) as e:
                errors.append((p, e))
    return ok, errors


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out_root", required=True,
                     help="Root directory to walk for *.md files, e.g. "
                          "../runs/csv_base_2.5_20/best_archs_plots")
    ap.add_argument("--workers", type=int, default=16)
    args = ap.parse_args()

    out_root = Path(args.out_root).resolve()
    if not out_root.is_dir():
        raise SystemExit(f"--out_root not found: {out_root}")

    ok, errors = render_tree(out_root, args.workers)
    print(f"done: {ok} converted, {len(errors)} errors")
    for p, e in errors:
        print(f"  FAILED {p}: {e}")


if __name__ == "__main__":
    main()
